<?php
$hours = $details->opening_hours;
echo $args['before_widget']
?>
<div class="daily-hours">
	The museum is currently
	<?php if($hours->open_now): ?>
	<p class="museum-status museum-open">
		OPEN
	</p>
	until <?php
	$today = date('w');
	foreach($hours->periods as $day)
	{
		if($today == $day->open->day) {
			echo date('g:i a', strtotime($day->close->time));
		}
	}
	else: ?>
	<p class="museum-status museum-closed">
		CLOSED
	</p>
	until <?php
		foreach($hours->periods as $day)
		{
			$today = (date('w') == 6 && date('Hi') > $day->open->time) ? -1 : date('w');
			if($today <= $day->open->day){
				echo \psrm\controllers\GooglePlaces::$dowMap[$day->open->day] . ': ' . date('g:i a', strtotime($day->open->time)) . ' - ' . date('g:i a', strtotime($day->close->time));
				break;
			}
		}
		?>
	<?php endif; ?>
</div>
<?php echo $args['after_widget']; ?>