<div class="form-group donation-form">
	<label for="amount">Choose Amount:</label>

	<div class="row">
		<?php foreach ( $donation_amounts as $key => $amount ): ?>
			<div class="col-sm-4 donation-amount-input">
				<input type="radio" class="donation_amount_form" id="amount<?php echo $key; ?>"
				       name="amount"
				       data-amount="<?php echo $amount; ?>"
				       value="<?php echo $key; ?>">&nbsp;<label
					for="amount<?php echo $key; ?>">$<?php echo $amount; ?></label>
			</div>
		<?php endforeach; ?>
	</div>
	<?php if ( $allow_custom_amount ): ?>
		<input type="radio" class="donation_amount_form" id="amount_custom" name="amount"
		       value="custom">&nbsp;<label for="amount_custom">Custom</label>
		<div class="input-group custom-donation-group hidden">
			<div class="input-group-addon fa fa-usd"></div>
			<input type="text" class="form-control" id="custom_amount" name="custom_amount" placeholder="Amount">

			<div class="input-group-addon">USD</div>
		</div>
	<?php endif; ?>
</div>
<div class="donate-button-error"></div>
<button type="button" class="btn btn-primary btn-lg donation-button" onclick="ga('send', 'event', 'Donate Button', 'Click', 'Donation Page');">
	Donate Today
</button>


<div class="modal fade bs-example-modal-sm donation-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
     aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
						aria-hidden="true">&times;</span></button>
				<div class="aligncenter">Processing Donation</div>
			</div>
			<div class="modal-body">

			</div>
		</div>
	</div>
</div>
<div class="donation-analytics"></div>
<script type="text/javascript" src="https://checkout.stripe.com/checkout.js"></script>