<?php
/** @var array $donation_funds */
/** @var array $donation_amounts */
/** @var string $allow_custom_amount */
/** @var int $custom_donation_floor */
?>
<div class="form-group donation-form">
	<label for="donation_fund">Choose Fund:</label>

	<div class="row">
		<div class="col-sm-4 donation-fund-select">
			<select name="donation_fund" class="donation_fund" id="donation_fund">
				<?php foreach ( $donation_funds as $key => $fund ): ?>
					<option id="<?= $key ?>"><?= $fund ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<label for="amount">Choose Amount:</label>

	<div class="row">
		<?php foreach ( $donation_amounts as $key => $amount ): ?>
			<div class="col-sm-4 donation-amount-input">
				<input type="radio" class="donation_amount_form" id="amount<?php echo $key; ?>"
				       <?php if($key === array_key_first($donation_amounts)): ?> checked <?php endif; ?>
                       name="amount"
				       data-amount="<?php echo $amount; ?>"
				       value="<?php echo $key; ?>">&nbsp;<label
					for="amount<?php echo $key; ?>">$<?php echo $amount; ?></label>
			</div>
		<?php endforeach; ?>
	</div>
	<?php if ( $allow_custom_amount ): ?>
		<input type="radio" class="donation_amount_form" id="amount_custom" name="amount"
		       value="custom">&nbsp;<label for="amount_custom">Custom</label>
		<div class="input-group custom-donation-group hidden">
			<div class="input-group-addon fa fa-usd"></div>
			<input type="text" class="form-control" id="custom_amount" name="custom_amount" placeholder="Amount">

			<div class="input-group-addon">USD</div>
		</div>
	<?php endif; ?>
    <div class="input-group">
    <input type="checkbox" checked id="pay_fees" name="pay_fees"/>
    <label for="pay_fees">&nbsp;Pay the processing fee</label>
    </div>
</div>
<div class="donate-button-error"></div>
<button type="button" class="btn btn-primary btn-lg donation-button">
	Donate
</button>
