<?php

$args = [
	'post_type' => 'service_alerts',
	'posts_per_page' => -1,
];
$service_alert_query = new WP_Query($args);
?>

<?php if($service_alert_query->have_posts()): ?>

	<div class="psrm-service-alerts" id="psrm-service-marquee">
	<ul>
	<?php while($service_alert_query->have_posts()): $service_alert_query->the_post(); ?>
		<li><a href="<?php the_permalink(); ?>">
			<?php the_title('<strong>', '</strong>'); ?>
		</a></li>
	<?php endwhile; ?>
	<?php wp_reset_postdata(); ?>
	</ul>
	</div>

<?php endif; ?>