<h3>Google Places Settings</h3>

<table class='form-table'>
	<tr>
		<th scope="row">Google API Key</th>

		<td>
			<input type='text' class='regular-text' id='google-places-api-key' value='<?php echo $settingsModel->getOption('google_places_api_key', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('google_places_api_key', $current_tab) ?>' />

		</td>

	</tr>

	<tr>
		<th scope="row">Google Places ID</th>

		<td>
			<input type='text' class='regular-text' id='google-places-id' value='<?php echo $settingsModel->getOption('google_places_id', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('google_places_id', $current_tab) ?>' />

		</td>

	</tr>

</table>

<?php submit_button(); ?>