<?php
/** @var string $current_tab */
/** @var psrm\models\Settings $settingsModel */
?>

<h3>Google reCAPTCHA Settings</h3>

<table class='form-table'>
	<tr>
		<th scope="row"><label for="site-key">Site Key</label></th>

		<td>
			<input type='text' class='regular-text' id='site-key' value='<?php echo $settingsModel->getOption('google_recaptcha_site_key', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('google_recaptcha_site_key', $current_tab) ?>' />

		</td>

	</tr>

	<tr>
		<th scope="row"><label for="secret-key">Secret Key</label></th>

		<td>
			<input type='text' class='regular-text' id='secret-key' value='<?php echo $settingsModel->getOption('google_recaptcha_secret_key', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('google_recaptcha_secret_key', $current_tab) ?>' />

		</td>

	</tr>

</table>

<?php submit_button(); ?>
