<?php extract($vars); ?>

<h3>Stripe Settings</h3>

<table class='form-table'>
	<tr>
		<th scope="row"><label for="stripe-secret-key">Secret Key:</label></th>

		<td>
			<input type='text' class='regular-text' id='stripe-secret-key' value='<?php echo $settingsModel->getOption('stripe_secret_key', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('stripe_secret_key', $current_tab) ?>' />

		</td>

	</tr>

	<tr>
		<th scope="row"><label for="stripe-public-key">Public Key</label></th>

		<td>
			<input type='text' class='regular-text' id='stripe-public-key' value='<?php echo $settingsModel->getOption('stripe_public_key', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('stripe_public_key', $current_tab) ?>' />

		</td>

	</tr>

	<tr>
		<th scope="row"><label for="checkout-image-url">Checkout Image URL</label></th>

		<td>
			<input type='text' class='regular-text' id='checkout-image-url' value='<?php echo $settingsModel->getOption('checkout_image_url', $current_tab) ?>'
			       name='<?php echo $settingsModel->getInputName('checkout_image_url', $current_tab) ?>' />

		</td>

	</tr>

</table>

	<h3>Donation Amounts</h3>

	<ul class="donation-amounts editable">
		<?php if ( $donations = $settingsModel->getOption( 'donation_amounts', $current_tab ) ):
			$donation_option_name = $settingsModel->getInputName( 'donation_amounts', $current_tab );
			foreach ( $donations as $amount ): ?>
				<li><input type="hidden"
				           name="<?php echo $donation_option_name; ?>[]"
				           value="<?php echo $amount; ?>"><span title="Drag to reposition" class="drag-handle">&#9776;</span><?php echo $amount; ?>
					<i class="js-remove" title="Click to remove">✖</i></li>
			<?php endforeach; ?>
		<?php endif; ?>
	</ul>
	<label for="add_amount">Add Amount</label> <input
	type="number" id="add_amount"><input type="hidden" id="add_amount_name"
	                       value="<?php echo $settingsModel->getInputName( 'donation_amounts', $current_tab ); ?>"><?php submit_button( 'Add', 'secondary', 'add_amount_button', false ); ?>

<p><input type="checkbox" id="allow_custom_name" name="<?php echo $settingsModel->getInputName('allow_custom_amount', $current_tab); ?>" <?php echo $settingsModel->getOption('allow_custom_amount', $current_tab) ? 'checked' : '';?> />
<label for="allow_custom_name">Allow customer to specify their own donation amount.</label>
<br>
<label for="custom_donation_floor">Do not allow custom donations below: $</label><input type="number" id="custom_donation_floor" name="<?php echo $settingsModel->getInputName('custom_donation_floor', $current_tab); ?>" value="<?php echo $settingsModel->getOption('custom_donation_floor', $current_tab); ?>">
</p>

	<h3>Emails</h3>
	<ul class="email-successful-donation editable">
		<?php if ( $emails = $settingsModel->getOption( 'email_successful_donation', $current_tab ) ):
			$email_option_name = $settingsModel->getInputName( 'email_successful_donation', $current_tab );
			foreach ( $emails as $email ): ?>
				<li><input type="hidden" name="<?php echo $email_option_name; ?>[]" value="<?php echo $email; ?>">
					<span title="Drag to reposition" class="drag-handle">&#9776;</span><?php echo $email; ?>
					<i class="js-remove" title="Click to remove">✖</i></li>
			<?php endforeach; ?>
		<?php endif; ?>
	</ul>
	<label for="add_email">Add Email</label>
	<input type="text" id="add_email"><input type="hidden" id="add_email_name"
	                                         value="<?php echo $settingsModel->getInputName( 'email_successful_donation', $current_tab ); ?>"><?php submit_button( 'Add', 'secondary', 'add_email_button', false ); ?>

<?php submit_button(); ?>