<button type="button" class="btn btn-primary btn-lg donation-button" data-toggle="modal" data-target=".bs-example-modal-sm">☺ Donate Today</button>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<div class="aligncenter">Make A One-Time Donation to Pacific Southwest Railway Museum</div>
			</div>
			<div class="modal-body">
				<form class="anet-donation">
					<div class="form-group">
						<label for="amount" class="control-label sr-only"">Amount:</label>
						<div class="input-group">
							<div class="input-group-addon">$</div>
							<input type="text" class="form-control" id="amount" placeholder="Amount">
							<div class="input-group-addon">USD</div>
						</div>
					</div>
					<div class="form-group">
						<label for="cc_num" class="control-label sr-only"">Credit Card Number:</label>
						<div class="input-group">
							<div class="input-group-addon glyphicon glyphicon-credit-card"></div>
							<input type="text" class="form-control" id="cc_num" placeholder="Credit Card Number">
						</div>
					</div>
					<div class="form-group">
						<label for="expiration" class="control-label sr-only"">Expiration:</label>
						<div class="input-group">
							<div class="input-group-addon glyphicon glyphicon-calendar"></div>
							<input type="text" class="form-control" id="expiration" placeholder="MM/YY">
						</div>
						<label for="cvc" class="control-label sr-only"">CVC:</label>
						<div class="input-group">
							<div class="input-group-addon glyphicon glyphicon-lock"></div>
							<input type="text" class="form-control" id="cvc" placeholder="CVC">
						</div>
					</div>
					<hr/>
					<div class="small">The following is optional and is only needed if you want a donation receipt mailed to you.</div>
					<div class="form-group">
						<label for="name" class="control-label sr-only"">Name on Card:</label>
						<div class="input-group">
							<div class="input-group-addon glyphicon glyphicon-user"></div>
							<input type="text" class="form-control" id="name" placeholder="Name on Card">
						</div>
						<label for="address" class="control-label sr-only"">Address:</label>
						<div class="input-group">
							<div class="input-group-addon glyphicon glyphicon-envelope"></div>
							<input type="text" class="form-control" id="address" placeholder="Address">
						</div>
					</div>
					<input type="submit" value="Make Donation" class="btn btn-primary">
				</form>
			</div>
		</div>
	</div>
</div>
