<?php
// Function to return the JavaScript representation of a TransactionData object.
function getTransactionJs(&$trans) {
	return <<<HTML
ga('ecommerce:addTransaction', {
  'id': '{$trans['id']}',
  'revenue': '{$trans['revenue']}',
});
HTML;
}

// Function to return the JavaScript representation of an ItemData object.
function getItemJs(&$transId, &$item) {
	return <<<HTML
ga('ecommerce:addItem', {
  'id': '$transId',
  'name': '{$item['name']}',
  'sku': '{$item['sku']}',
  'category': '{$item['category']}',
  'price': '{$item['price']}',
  'quantity': '{$item['qty']}',
});
HTML;
}
?>

<script>
	ga('require', 'ecommerce');

	<?php
	echo getTransactionJs($trans);

	foreach ($items as &$item) {
	  echo getItemJs($trans['id'], $item);
	}
	?>

	ga('ecommerce:send');
</script>